
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xacN`\x01\xc5\xed\x08$\xc9\xa0\x17\xbbB\xb1\xd9A'
    
_lr_action_items = {'PLAIN':([2,],[4,]),'H1OPEN':([0,],[2,]),'H1CLOSE':([3,4,],[5,-2,]),'$end':([1,5,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'plain':([2,],[3,]),'h1':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> h1","S'",1,None,None,None),
  ('h1 -> H1OPEN plain H1CLOSE','h1',3,'p_h1','/Users/leapoahead/Code/cp-project/src/prac/yacct2.py',6),
  ('plain -> PLAIN','plain',1,'p_plain','/Users/leapoahead/Code/cp-project/src/prac/yacct2.py',10),
]
